### PR TITLE
spidermultusconfig: set default value if it not set

### PR DESCRIPTION
**Pull request by cyclinder**
#### What type of PR is this?

 - release/none 
 - kind/cleanup

**What this PR does / why we need it**:

spidermultusconfig: set default value if it not set

**Which issue(s) this PR fixes**:

Fixes https://github.com/spidernet-io/spiderpool/issues/2430

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Icarus9913** [comment]
所有 "omitempty" tag全部保留住，
在spidermultusconfig.spec.coordinator上一行，补充
`// +kubebuilder:default={}`试试看

**Comment by weizhoublue** [comment]
@Icarus9913 @cyclinder  be able to merge ？

**Comment by cyclinder** [comment]
Nope, It still need more tests.

**Comment by cyclinder** [comment]
It's ok to merge this, https://github.com/spidernet-io/spiderpool/actions/runs/6888292072/job/18737001510?pr=2603 is excpeted, We have mutate webhook for spidermultusconfig in the changes, but `v0.8.0` don't have the logic code for mutate webhook for spidermultusconfig.

**Pull request merged**
