### PR TITLE
spidermultusconfig: remove redundant field "resourceName"

### PR DESCRIPTION
**Pull request by cyclinder**
---
name: Pull request
about: Tell us about your contribution
labels: ["pr/release/none-required"]
---

---
## Thanks for contributing !

Before submitting a pull request, make sure you read about our Contribution notice here: <https://spidernet-io.github.io/spiderpool/contributing/development/pullrequest/#need-review>

**What this PR does / why we need it**:

spidermultusconfig: remove redundant field "resourceName"

**Which issue(s) this PR fixes**:

https://github.com/spidernet-io/spiderpool/issues/2133

**Special notes for your reviewer**:

**make sure your commit is signed off**

### CODE REVIEW

**Comment by weizhoublue** [comment]
I think it could add E2E for spidermultusconfig and accurately test the expected kinds of generated multus CR
@cyclinder @ty-dc

**Comment by cyclinder** [comment]
https://github.com/spidernet-io/spiderpool/pull/2138

**Comment by weizhoublue** [comment]
please add required E2E in the test/doc

**Comment by cyclinder** [comment]
updated.

**Pull request merged**
