### PR TITLE
E2E: testing if neither kubeadm-config nor kube-controller-manager no found

### PR DESCRIPTION
**Pull request by cyclinder**
#### What type of PR is this?

- release/none 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by weizhoublue — APPROVED** [review]

**Comment by cyclinder** [comment]
waiting for https://github.com/spidernet-io/spiderpool/pull/3291 be merged.

**Comment by weizhoublue** [comment]
it seems to need cherry-pick

**Comment by weizhoublue** [comment]
update

**Comment by weizhoublue** [comment]
is there any update

**Comment by cyclinder** [comment]
I'll take this soon.

**Review by weizhoublue — APPROVED** [review]

**Review by ty-dc — APPROVED** [review]

**Pull request merged**
