### PR TITLE
add spidernode crd

### LINKED ISSUE #2465: [feature] add spidernode CRD which preallocted ips for each node
**1 Code requirement**

**2 observe opensource license**

**3 sign-off your commit**

**4 Is your feature request related to a problem? Please describe.**

**5 Describe the solution you'd like**

Now in aws ECS environment could [eni-cni](https://github.com/aws/amazon-vpc-cni-k8s), and design like eni in [ciliumnodes resource](https://github.com/cilium/cilium/blob/aceea7df6e91964b61154e64b634d6ef320e4dc5/pkg/k8s/apis/cilium.io/v2/types.go#L374C45-L374C45) 
maybe spidernet could add another CRD, like spidernode which will preallocte ips for each node, because ip is from vpc, but only support ip not subnat, so spidernode record ip list which is preallocted. 

below is some likely steps:

- daemon(spider agent)
  - Use spidernode as the source for IP allocation
  - Synchronize spidernode and spiderpool resources
  - Can do some extra operations on nodes, such as adding network interfaces, setting IP/MAC etc.

- controller(spider controller)
  -  Create and update spidernode from spiderpool
  - Synchronize spec, status information with daemon decision

**6 Describe alternatives you've considered**

**7 Additional context**

### PR DESCRIPTION
**Pull request by yylt**
1 spidernode is local pool for ipam
2 support standerd and eni mode

mostly, controller will allocate some ipset from ippool which is for local used. in the spec.pools is all ips which include had allocated ip. In the eni mode, controller should update status.enis, when allocate ip, should check ip had in enis and status is ready

Signed-off-by: yylt <yang8518296@163.com>

#### What type of PR is this?

- release/feature
- label/feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2465

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by weizhoublue** [comment]
I think this does make sense just to add an CRD without any implementation, and it should give thoughts of difference between SpiderIIPool and SpiderNode

It could create an propose issue to give thoughts  to the detailed design.

**Comment by yylt** [comment]
> I think it does not make sense just to add an CRD without any implementation, directly into the main branch. It should give thoughts of difference between SpiderIIPool and SpiderNode
> 
> It could create an propose issue or join the wechat, to give thoughts to the detailed design.

agree

**Comment by cyclinder** [comment]
Would you like to join us on WeChat group? @yylt

**Comment by yylt** [comment]
> Would you like to join us on WeChat group? @yylt

yes, in slack i had asked，but nobody answer

**Pull request closed without merging**
