### PR TITLE
add some e2e for spiderpool

### PR DESCRIPTION
**Pull request by ty-dc**
**Which issue(s) this PR fixes**:
```
None
```

**make sure your commit is signed off**
Signed-off-by: ty-dc [tao.yang@daocloud.io](mailto:tao.yang@daocloud.io)

### CODE REVIEW

**Comment by weizhoublue** [comment]
fix the conflicts

**Comment by weizhoublue** [comment]
update

**Review by cyclinder — COMMENTED** [review]
Fix the CI: https://github.com/spidernet-io/spiderpool/actions/runs/7295885247/job/19882897540?pr=2246

**Comment by ty-dc** [comment]
> Fix the CI: https://github.com/spidernet-io/spiderpool/actions/runs/7295885247/job/19882897540?pr=2246

done

**Review by cyclinder — APPROVED** [review]

**Review by Icarus9913 — APPROVED** [review]

**Review by weizhoublue — APPROVED** [review]

**Pull request merged**
