### PR TITLE
improve coordiantor

### PR DESCRIPTION
**Pull request by cyclinder**
---
name: Pull request
about: Tell us about your contribution
labels: ["pr/release/none-required"]
---

---
## Thanks for contributing !

Before submitting a pull request, make sure you read about our Contribution notice here: <https://spidernet-io.github.io/spiderpool/contributing/development/pullrequest/#need-review>

**What this PR does / why we need it**:

improve coordiantor

**Which issue(s) this PR fixes**:

https://github.com/spidernet-io/spiderpool/issues/1870
https://github.com/spidernet-io/spiderpool/issues/1869

**Special notes for your reviewer**:

**make sure your commit is signed off**

### CODE REVIEW

**Comment by cyclinder** [comment]
```
---------spiderpool-agent-4rnwt--------
error, in spiderpool-agent-4rnwt, found error, Goroutine took lock !!!!!!!
{"level":"WARN","ts":"2023-06-07T03:39:03.036Z","logger":"Debug-Lock","caller":"lock/lock_debug.go:110","msg":"Goroutine took lock for more than 0.20 seconds","Seconds":0.221635749,"Goroutine":" 3570"}
```

**Comment by cyclinder** [comment]
PTAL

/cc @weizhoublue

**Comment by weizhoublue** [comment]
pelease update

**Comment by weizhoublue** [comment]
可以在 doc/concept 放一份 md，说明下 配置

**Comment by cyclinder** [comment]
> 可以在 doc/concept 放一份 md，说明下 cni 配置

在 https://github.com/spidernet-io/spiderpool/pull/1934 中一并处理

**Pull request merged**
