### PR TITLE
update governance document link

### PR DESCRIPTION
**Pull request by cyclinder**
#### What type of PR is this?

- release/none 

**What this PR does / why we need it**:

update governance document link

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by weizhoublue** [comment]
ready for merging ?

**Comment by cyclinder** [comment]
yes

**Comment by cyclinder** [comment]
wait...

**Comment by cyclinder** [comment]
it's ready to be merged

**Pull request merged**
