### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Roronoa-Z3r0**

### CODE REVIEW

**Comment by windsonsea** [comment]
Hi, could you run a command before commit in your local repo folder:

```
make lint-markdown-spell-colour
```
Then it may prompt you that `x86` is a wrong word. In fact, it is correct. You can add `x86` to the bottom of `.github/.spelling`.

For details, see [PR flow](https://github.com/spidernet-io/spiderpool/blob/main/docs/develop/pullrequest.md).

**Comment by Roronoa-Z3r0** [comment]
> Hi, could you run a command before commit in your local repo folder:
> 
> ```
> make lint-markdown-spell-colour
> ```
> 
> Then it may prompt you that `x86` is a wrong word. In fact, it is correct. You can add `x86` to the bottom of `.github/.spelling`.
> 
> For details, see [PR flow](https://github.com/spidernet-io/spiderpool/blob/main/docs/develop/pullrequest.md).

ok , I have resubmitted the code

**Comment by weizhoublue** [comment]
fixed @ https://github.com/spidernet-io/spiderpool/commit/0b2888456e19b899b6ef7527e9e79e742e254b45
thanks for the PR

**Pull request closed without merging**
