### PR TITLE
add link-local IP to veth0 for istio

### PR DESCRIPTION
**Pull request by weizhoublue**
robot cherry pick PR <https://github.com/spidernet-io/spiderpool/pull/3588> from cyclinder,to branch release-v0.9,  action <https://github.com/spidernet-io/spiderpool/actions/runs/9609000879>  , commits 13c95f09d9040352c02750cb8d8d970feea319f5

### CODE REVIEW

**Comment by weizhoublue** [comment]
@ty-dc  ci

**Comment by ty-dc** [comment]
The code merged into release-v0.9 triggers the pull_request_target to use the image of the main branch.

**Comment by weizhoublue** [comment]
```
     fail to run a pod when IP resource of an ippool is exhausted and an IP who is set in excludeIPs field of ippool, should not be assigned to a pod [E00008, S00002]

```

**Comment by ty-dc** [comment]
```
Warning  FailedCreatePodSandBox  4m38s (x17 over 8m8s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "915253528605f96a4db27301569495040e6e5bfd93e55e643aff6b04711acd4e": plugin type="multus" name="multus-cni-network" failed (add): [ns187-858559962/deploy187-858549683-5b4569f6dc-qrqk7/7a54422a-5a39-4650-8e1d-07d5d67ab318:macvlan-vlan0]: error adding container to network "macvlan-vlan0": spiderpool IP allocation error: [POST /ipam/ip][500] postIpamIpFailure  failed to allocate IP addresses in standard mode: it's invalid to use 'ipam.spidernet.io/subnets' or 'ipam.spidernet.io/subnet' annotation when Auto-Pool feature is disabled
```
The upgrade-ci command in cherry-pick fails due to an image usage error.

**Review by ty-dc — APPROVED** [review]

**Pull request merged**
